name: la_contree
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.42
  path: ^1.9.1
  intl: ^0.20.2
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.3.2
  flutter_map: ^8.3.1
  geolocator: ^14.0.2
  latlong2: ^0.10.1
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logos.png"
  adaptive_icon_background: "#0B5A8C"  # Bleu Océan (palette)
  adaptive_icon_foreground: "assets/images/logos.png"
  remove_alpha_ios: true
